apiVersion: v1
kind: Service
metadata:
  namespace: sandbox
  name: takahiro-yamakawa-handson
spec:
  selector:
    app: takahiro-yamakawa-handson
  ports:
  - protocol: TCP
    port: 80  # Pod で特権 port に bind しなくても、Service ではつけられる
    targetPort: http
